// Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/16、原始数据管理方式和Vuex/1、原始方式/src/components/count.vue
<!--
  ~ Time:2022/3/2 21:46 34
  ~ Name:count.vue
  ~ Path:Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/src/components
  ~ ProjectName:WWW
  ~ Author:charlatan
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->

<template>
  <div>
    <h2>当前的和是：{{ sum }}</h2>
    &nbsp;
    <select v-model.number="num">
      <option :value=1 class="js-options-table">1</option>
      <option :value=2 class="js-options-table">2</option>
      <option :value=3 class="js-options-table">3</option>
    </select>
    &nbsp;
    <button class="btn btn-warning" @click="add">+</button>
    &nbsp;
    <button class="btn btn-warning" @click="deadd">-</button>
    &nbsp;
    <button class="btn btn-warning" @click="addOdd">奇数再加</button>
    &nbsp;
    <button class="btn btn-warning" @click="addWait">等会在加</button>
  </div>
</template>

<script>
export default {
  name: 'count',
  data () {
    return {
      sum: 0,
      num: 1,
    }
  },
  components: {},
  methods: {
    add () {
      this.sum += this.num
    },
    deadd () {
      this.sum -= this.num
    },
    addOdd () {
      if (this.sum % 2 !== 0) {
        this.add()
      }
    },
    addWait () {
      setTimeout(this.add, 2000)
    },
  },
}
</script>

<style scoped>

</style>

// com/charlatan/self_study/React/react_scaffold/main/10、react-redux/1、react-redux的基本使用/src/components/Count/index.jsx
/**
 * Time:2022/3/27 19:14 50
 * Name:index.jsx
 * Path:src/components/Count
 * ProjectName:react_scaffold
 * Author:charlatan
 *
 *  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
 */

import React, { Component } from 'react'

export default class Count extends Component {
  selectRef = React.createRef()
  
  render () {
    console.log(this.props);
    return (
      <div id="Count">
        <h1>当前求和为：{this.props.count}</h1>
        
        <select ref={this.selectRef}>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
        </select>
        
        <button onClick={this.add}>+</button>
        <button onClick={this.subtract}>-</button>
        <button onClick={this.oddAdd}>奇数再加</button>
        <button onClick={this.waitAdd}>等等再加</button>
      
      </div>
    )
    
  }
  
  add = () => {
    let num = parseInt(this.selectRef.current.value)
    this.props.add(num)
  }
  subtract = () => {
    let num = parseInt(this.selectRef.current.value)
    this.props.subtract(num)
  }
  oddAdd = () => {
    let num = parseInt(this.selectRef.current.value)
    if (this.props.count % 2){
      this.props.add(num)
    }
  }
  waitAdd = () => {
    let num = parseInt(this.selectRef.current.value)
    this.props.asyncAdd(num,1000)
  }
}
