// Web/src/com/charlatan/self_study/React/react_scaffold/main/9、redux/4、异步action/src/components/Count/index.jsx
/**
 * Time:2022/3/27 19:14 50
 * Name:index.jsx
 * Path:src/components/Count
 * ProjectName:react_scaffold
 * Author:charlatan
 *
 *  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
 */

import React, { Component } from 'react'
import store from '../../redux/store'
import { createAppAction, createAsyncAdd, createSubtractAction } from '../../redux/count_action'

export default class Count extends Component {
    selectRef = React.createRef()
    
    render () {
        console.log(store.getState())
        return (
            <div id="Count">
                <h1>当前求和为：{store.getState()}</h1>
                
                <select ref={this.selectRef}>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                </select>
                
                <button onClick={this.add}>+</button>
                <button onClick={this.subtract}>-</button>
                <button onClick={this.oddAdd}>奇数再加</button>
                <button onClick={this.waitAdd}>等等再加</button>
            
            </div>
        )
        
    }
    
    add = () => {
        let num = parseInt(this.selectRef.current.value)
        store.dispatch(createAppAction(num))
        
    }
    subtract = () => {
        let num = parseInt(this.selectRef.current.value)
        store.dispatch(createSubtractAction(num))
    }
    oddAdd = () => {
        let num = parseInt(this.selectRef.current.value)
        if (store.getState() % 2) {
            store.dispatch(createAppAction(num))
            
        }
    }
    waitAdd = () => {
        let num = parseInt(this.selectRef.current.value)
        store.dispatch(createAsyncAdd(num, 1000))
        
    }
}

// Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/16、原始数据管理方式和Vuex/3、getters的使用/src/components/count.vue
<!--
  ~ Time:2022/3/2 21:46 34
  ~ Name:count.vue
  ~ Path:Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/src/components
  ~ ProjectName:WWW
  ~ Author:charlatan
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->

<template>
  <div>
    <h2>当前的和是：{{ $store.state.sum }}</h2>
    &nbsp;<h2> 当前这个数字乘10的结果时：{{ $store.getters.calculate }}</h2>
    <select v-model.number="num">
      <option :value=1 class="js-options-table">1</option>
      <option :value=2 class="js-options-table">2</option>
      <option :value=3 class="js-options-table">3</option>
    </select>
    &nbsp;
    <button class="btn btn-warning" @click="add">+</button>
    &nbsp;
    <button class="btn btn-warning" @click="deadd">-</button>
    &nbsp;
    <button class="btn btn-warning" @click="addOdd">奇数再加</button>
    &nbsp;
    <button class="btn btn-warning" @click="addWait">等会在加</button>
  </div>
</template>

<script>
export default {
  name: 'count',
  data () {
    return {
      num: 1,
    }
  },
  components: {},
  methods: {
    add () {
      // 因为逻辑业务简单，直接联系 mutations
      // this.$store.dispatch('add', this.num)
      this.$store.commit('ADD', this.num)
    },
    deadd () {
      this.$store.commit('DEADD', this.num)
    },
    addOdd () {
      this.$store.dispatch('addOdd', this.num)
    },
    addWait () {
      this.$store.dispatch('addWait', this.num)
    },
  },
  mounted () {
    console.log(this)
  },
}
</script>

<style scoped>

</style>
