// Web/src/com/charlatan/self_study/React/react_scaffold/main/9、redux/1、原生React实现求和案例/src/components/Count/index.jsx
/**
 * Time:2022/3/27 19:14 50
 * Name:index.jsx
 * Path:src/components/Count
 * ProjectName:react_scaffold
 * Author:charlatan
 *
 *  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
 */

import React, { Component } from 'react'

export default class Count extends Component {
    selectRef = React.createRef()
    
    render () {
        let { count } = this.state
        return (
            <div id="Count">
                <h1>当前求和为：{count}</h1>
                
                <select ref={this.selectRef}>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                </select>
                
                <button onClick={this.add}>+</button>
                <button onClick={this.subtract}>-</button>
                <button onClick={this.oddAdd}>奇数再加</button>
                <button onClick={this.waitAdd}>等等再加</button>
            
            </div>
        )
        
    }
    
    state = {
        count: 0,
    }
    
    add = () => {
        let num = parseInt(this.selectRef.current.value)
        let count = num + this.state.count
        this.setState({
            count,
        })
    }
    subtract = () => {
        let num = parseInt(this.selectRef.current.value)
        let count = num - this.state.count
        this.setState({
            count,
        })
    }
    oddAdd = () => {
        let { count } = this.state
        let num = parseInt(this.selectRef.current.value)
        if (count % 2) {
            let count = num + this.state.count
            this.setState({
                count,
            })
        }
    }
    waitAdd = () => {
        let num = parseInt(this.selectRef.current.value)
        setTimeout(() => {
            let count = num + this.state.count
            this.setState({
                count,
            })
        }, 1000)
    }
}

// com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/16、原始数据管理方式和Vuex/1、原始方式/src/components/count.vue
<!--
  ~ Time:2022/3/2 21:46 34
  ~ Name:count.vue
  ~ Path:Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/src/components
  ~ ProjectName:WWW
  ~ Author:charlatan
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->

<template>
  <div>
    <h2>当前的和是：{{ sum }}</h2>
    &nbsp;
    <select v-model.number="num">
      <option class="js-options-table" :value=1>1</option>
      <option class="js-options-table" :value=2>2</option>
      <option class="js-options-table" :value=3>3</option>
    </select>
    &nbsp;
    <button class="btn btn-warning" @click="add">+</button>
    &nbsp;
    <button class="btn btn-warning" @click="deadd">-</button>
    &nbsp;
    <button class="btn btn-warning" @click="addOdd">奇数再加</button>
    &nbsp;
    <button class="btn btn-warning" @click="addWait">等会在加</button>
  </div>
</template>

<script>
export default {
  name: 'count',
  data () {
    return {
      sum: 0,
      num: 1,
    }
  },
  components: {},
  methods: {
    add () {
      this.sum += this.num
    },
    deadd () {
      this.sum -= this.num
    },
    addOdd () {
      if (this.sum % 2 !== 0) {
        this.add()
      }
    },
    addWait () {
      setTimeout(this.add, 2000)
    },
  },
}
</script>

<style scoped>

</style>
