// Web/src/com/charlatan/self_study/React/react_scaffold/main/7、React-Router -- 5/8、编程式路由导航/src/pages/About/index.jsx
/**
 * Time:2022/3/26 18:49 07
 * Name:index.jsx
 * Path:src/components/About
 * ProjectName:react_scaffold
 * Author:charlatan
 *
 *  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
 */

import React, { Component } from 'react'

export default class About extends Component {
    
    render () {
        return (
            <h1>这个是 About 中的内容</h1>
        )
    }
    
}

// com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/17、路由/11、路由的两种模式/src/pages/about.vue
<!--
  ~ Time:2022/3/4 17:33 21
  ~ Name:about.vue
  ~ Path:Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/src/components
  ~ ProjectName:WWW
  ~ Author:charlatan
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->

<template>
  <h1>
    我是about中的内容
  </h1>
</template>

<script>
export default {
  name: 'about',
  data () {
    return {}
  },
  components: {},
}
</script>

<style scoped>

</style>
