// com/charlatan/self_study/React/react_scaffold/main/5、GitHub搜索/src/components/Search/index.jsx
/**
 * Time:2022/3/25 22:04 42
 * Name:index.jsx
 * Path:src/components/Search
 * ProjectName:react_scaffold
 * Author:charlatan
 *
 *  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
 */

import React, { Component } from 'react'
import './index.css'
import axios from 'axios'

export default class Search extends Component {
	inputValue = React.createRef ()
	
	render () {
		return (
				<div id="Search">
					<h1 className="span">输入内容开始搜索</h1>
					<input
							type="text"
							ref={this.inputValue}
							className="input"
							placeholder=" 输入关键字"/>
					<button className="btn" onClick={this.sendAsk}>搜索</button>
				</div>
		)
	}
	
	sendAsk = () => {
		let value = this.inputValue.current.value
		this.props.updateList ([1], true, true)
		
		if ( value.trim () === '' ) {
			alert ('输入不能为空')
			this.inputValue.current.value = ''
		} else {
			
			axios.get ('https://api.g ithub.com/search/users?q=' + this.inputValue.current.value).then (
					(res) => {
						this.props.updateList (res.data.items, false, true)
					},
					(reason) => {
						console.log (reason.message)
						this.props.updateList ([2], false, false, reason.message)
					},
			)
		}
	}
}

// Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/7、TodoList案例/components/search.vue
<!--
  ~ Time:2022/2/24 15:35 37
  ~ Name:search.vue
  ~ Path:Web代码/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/src/components
  ~ ProjectName:WWW
  ~ Author:charlatan
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->

<template>
  <div>
    <input v-model:value="value" class="search" placeholder="输入内容开始搜索" type="search" @keydown.enter="add">
  </div>
</template>

<script>
import { nanoid } from 'nanoid'

export default {
  name: 'search',
  data () {
    return {
      value: '',
    }
  },
  methods: {
    add () {
      let value = this.value.trim()
      if (value === '') {
        console.log('请输入内容')
        this.value = ''
      } else {
        this.addObj({ id: nanoid(), value, done: false })
        this.value = ''
      }
    },
  },
  components: {},
  props: {
    addObj: Function,
    // all: Number,
  },
}
</script>

<style lang="less" scoped>
.search {
  width: 400px;
  height: 50px;
  border-radius: 5px;
  position: relative;
  top: 20px;
  left: 80px;
  outline: none;

  &:focus {
    box-shadow: 0 0 3px 3px #bcc3ce;
  }

  &::placeholder {
    padding-left: 5px;
  }
}
</style>
