// com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/github用户案例/components/search.vue
<!--
  ~ Time:2022/3/2 15:17 20
  ~ Name:search.vue
  ~ Path:Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/src/components
  ~ ProjectName:WWW
  ~ Author:charlatan
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->

<template>
  <div>
    <span>开始搜索</span>
    <br>
    <br>
    <input id="input" v-model.trim.lazy='value' name="" placeholder="点击开始搜索" type="text">
    &nbsp;&nbsp;
    <button class="btn btn-warning" @click="search">搜索</button>
  </div>
</template>

<script>
import axios from 'axios'

export default {
  name: 'search',
  data () {
    return {
      value: '',
    }
  },
  components: {},
  methods: {
    search () {
      if ( this.value !== '' ) {
        this.$bus.$emit ('wait', '', false)
        let userArr = []
        console.log ('开始搜索', this.value)
        axios.get ('https://api.github.com/search/users?q=' + this.value).then ((res) => {
          for ( let item of res.data.items ) {
            userArr.push ({
              img: item.avatar_url,
              id: item.id,
              username: item.login,
            })
          }
          this.$bus.$emit ('sends', userArr)
        }, (err) => {
          this.$bus.$emit ('wait', err, true)
          console.log (err)
        })
      }
    },
  },
}
</script>

<style scoped>

</style>

// com/charlatan/self_study/React/react_scaffold/main/5、GitHub搜索/src/components/Search/index.jsx
/**
 * Time:2022/3/25 22:04 42
 * Name:index.jsx
 * Path:src/components/Search
 * ProjectName:react_scaffold
 * Author:charlatan
 *
 *  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
 */

import React, { Component } from 'react'
import './index.css'
import axios from 'axios'

export default class Search extends Component {
	inputValue = React.createRef ()
	
	render () {
		return (
				<div id="Search">
					<h1 className="span">输入内容开始搜索</h1>
					<input
							type="text"
							ref={this.inputValue}
							className="input"
							placeholder=" 输入关键字"/>
					<button className="btn" onClick={this.sendAsk}>搜索</button>
				</div>
		)
	}
	
	sendAsk = () => {
		let value = this.inputValue.current.value
		this.props.updateList ([1], true, true)
		
		if ( value.trim () === '' ) {
			alert ('输入不能为空')
			this.inputValue.current.value = ''
		} else {
			
			axios.get ('https://api.g ithub.com/search/users?q=' + this.inputValue.current.value).then (
					(res) => {
						this.props.updateList (res.data.items, false, true)
					},
					(reason) => {
						console.log (reason.message)
						this.props.updateList ([2], false, false, reason.message)
					},
			)
		}
	}
}
