// Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/17、路由/1、路由基本使用/src/components/home.vue
<!--
  ~ Time:2022/3/4 17:33 37
  ~ Name:home.vue
  ~ Path:Web/src/com/charlatan/self_study/Vue/Vue 2.x/基础/vue_test/src/components
  ~ ProjectName:WWW
  ~ Author:charlatan
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->

<template>
  <h1>
    我是home中的内容
  </h1>
</template>

<script>
export default {
  name: 'home',
  data () {
    return {}
  },
  components: {},
}
</script>

<style scoped>

</style>

// com/charlatan/self_study/React/react_scaffold/main/12、ReactRouter -- 6/3、Navlink指定高亮样式/src/components/Home/index.jsx
/**
 * Time:2022/3/26 18:49 39
 * Name:index.jsx
 * Path:src/components/Home
 * ProjectName:react_scaffold
 * Author:charlatan
 *
 *  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
 */

import React, { Component } from 'react'

export default class Home extends Component {
	
	render () {
		return (
				<h1>这是 Home 中的内容</h1>
		)
	}
	
}
